#!/usr/bin/env bash
# GraphRAG Regression — Recall@K Evaluation
#
# Measures retrieval quality using ground-truth supporting passages.
# For each question, checks what fraction of its ground-truth contexts appear
# in the top-K chunks retrieved by GraphRAG (default K=5).
#
# Dataset must contain ground_truth_chunks.csv (generated by build_gt_chunks.py
# from ground_truth_contexts.csv).  questions.csv is also required.
# answers.csv is NOT used here — this metric is purely about retrieval quality.
#
# This metric is independent of answer correctness and hallucination check.
# Run them separately with run_eval.sh.
#
# Usage (from repo root):
#
#   Default (Classic engine, auto retriever, K=5):
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --mode classic/auto
#
#   Specific retriever (for debugging only — use auto for product testing):
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --mode classic/similaritysearch
#
#   Agentic planned agent:
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --mode planned
#
#   Different K value:
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --k 10
#
#   Detailed per-question output (shows unmatched GT passages):
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --detailed
#
#   Limit to first N questions (quick smoke test):
#     ./graphrag/tests/regression/run_recall.sh --dataset Multihop30 --graphname multihop30_abc12345 --limit 5
#
# Override the container name with GRAPHRAG_CONTAINER if needed.
# Results are written to graphrag/tests/regression/results/ on the host.
# All arguments are forwarded to recall_evaluator.py.

set -euo pipefail

# Git Bash / MSYS on Windows rewrites "/code/..." into a Windows path.
# Disable that POSIX path conversion so the container path is preserved.
export MSYS_NO_PATHCONV=1
export MSYS2_ARG_CONV_EXCL="*"

CONTAINER="${GRAPHRAG_CONTAINER:-graphrag}"
REG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${REG_DIR}/_container_sync.sh"

sync_regression_to_container "${CONTAINER}" "${REG_DIR}"

# FORCE_COLOR=1 keeps colourised output even when docker exec output is piped.
# Set NO_COLOR=1 in your shell to turn colours off.
set +e
docker exec \
    -w /code \
    -e PYTHONUNBUFFERED=1 \
    -e PYTHONWARNINGS=ignore \
    -e FORCE_COLOR="${FORCE_COLOR:-1}" \
    -e NO_COLOR="${NO_COLOR:-}" \
    "${CONTAINER}" \
    python /code/tests/regression/recall_evaluator.py "$@"
rc=$?

copy_results_from_container "${CONTAINER}" "${REG_DIR}"
exit $rc
