FROM python:3.11-bullseye
WORKDIR /code

 
COPY ./graphrag/requirements.txt /code/requirements.txt

 
RUN apt-get update && apt-get upgrade -y
RUN pip install -r /code/requirements.txt

 
COPY ./graphrag/app /code/app
COPY ./common /code/app/common
COPY ./graphrag/tests /code/tests

COPY ./.git /code/.git

# INFO, DEBUG, DEBUG_PII
ENV LOGLEVEL="DEBUG"

WORKDIR /code/tests
